gmail:
  credentials: "./secrets/credentials.json"
  token: "./secrets/token.json"
  serviceName: "gmail"
  version: "v1"
  userId: "me"
  query: "has:attachment larger:1M"
batch:
  size: 10
target:
  folder: "/path/to/my/documents"